const $=s=>document.querySelector(s);let activeSpread=null,slotGeometry=[],shuffleTimer=null;let pendingCard=null;let deck=[],picked=[],shuffling=false,drag=null,suppressClick=false;const cardById=Object.fromEntries(CARDS.map(c=>[c.id,c]));
function randomInt(max){const a=new Uint32Array(1),limit=Math.floor(4294967296/max)*max;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
function shuffled(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function image(c,attrs=''){return `<img src="assets/${c.id}.jpg" alt="${c.name} · ${c.en}" ${attrs}>`}
function renderDeck(){ $('#deck').innerHTML=deck.map((x,i)=>`<button class="deck-card back" data-index="${i}" style="--i:${i%12}" aria-label="选择第 ${i+1} 张背面牌" ${shuffling||(activeSpread&&picked.length>=activeSpread.points.length)?'disabled':''} aria-pressed="${pendingCard===i}"></button>`).join('');$('#cancelPick').hidden=pendingCard===null;$('#remaining').textContent=`${deck.length} 张待选`;$('#tableCount').textContent=`已选 ${picked.length} 张`;$('#reverse').disabled=picked.length>0;$('#reveal').disabled=!picked.some(x=>!x.revealed)||shuffling}
function start(skipConfirm=false,keepQuestion=false){if(shuffling)return;if(!skipConfirm&&picked.length&&!confirm('重新洗牌会收起桌上的所有牌，并清空问题。开始新的一轮吗？'))return;shuffling=true;if(!keepQuestion)$('#readingQuestion').value='';pendingCard=null;picked=[];deck=shuffled(CARDS.map(c=>({id:c.id,rev:randomInt(2)===1})));$('#placed').innerHTML='';$('#empty').hidden=!!activeSpread;layoutSlots();$('#insight').innerHTML='<div class="aside-label">CARD READING <span>✦</span></div><div class="insight-empty"><span>☾</span><h2>每张牌，都是一个视角。</h2><p>翻开一张牌后，这里会显示它的正逆位含义与占星对应。</p><div class="mini-line"></div><p class="small">先感受画面，再阅读含义。<br>留一点空间，给自己的理解。</p></div>';$('#shuffle').disabled=true;renderDeck();$('#deck').scrollLeft=0;$('#deck').classList.add('shuffling');$('#status').textContent='正在洗牌，让牌序重新交错……';shuffleTimer=setTimeout(()=>{shuffling=false;$('#shuffle').disabled=false;$('#deck').classList.remove('shuffling');renderDeck();$('#status').textContent='牌已洗好。想好你的问题，然后选牌。'},850)}
function choose(index,point=null){if(shuffling||!deck[index])return;if(activeSpread){if(picked.length>=activeSpread.points.length){$('#status').textContent='这个牌阵已经选满，可以按顺序翻牌。';return}const target=slotGeometry[picked.length];if(!point||!insideSlot(point,target)){$('#status').textContent=`请把牌放入高亮的第 ${picked.length+1} 格。`;return}point={x:target.x,y:target.y}}pendingCard=null;const x=deck.splice(index,1)[0];x.rev=$('#reverse').checked&&x.rev;x.revealed=false;x.horizontal=false;picked.push(x);$('#empty').hidden=true;const i=picked.length-1;const el=document.createElement('div');el.className='table-card';el.dataset.order=activeSpread?.slotNames?.[i]??i+1;el.innerHTML=`<button class="flip" data-picked="${i}" aria-label="第 ${i+1} 张，背面朝上"><span class="flip-inner"><span class="face back"></span><span class="face front"></span></span></button><div class="card-caption">${String(i+1).padStart(2,'0')} · 待揭晓</div><button class="rotate-card" data-rotate="${i}" aria-label="将第 ${i+1} 张牌横放" title="横放／竖放（不改变正逆位）" aria-pressed="false">↻</button>`;$('#placed').append(el);if(activeSpread){x.horizontal=!!activeSpread.points[i][2];el.classList.toggle('horizontal',x.horizontal);el.style.zIndex=i+2;}const defaultPoint={x:.12+(i%5)*.19,y:.14+(Math.floor(i/5)%4)*.23};setPosition(i,point||defaultPoint);layoutSlots();renderDeck();$('#status').textContent=`已选第 ${i+1} 张。可以继续选牌，或翻开下一张。`}
function meaning(c,rev=false,both=false){return `<h2 class="reading-name">${c.name}</h2><div class="en">${c.en}</div>${both?'':`<span class="badge">${rev?'逆位 REVERSED':'正位 UPRIGHT'}</span>`}<div class="meaning"><h3>${both?'↑ 正位释义':rev?'↓ 逆位释义':'↑ 正位释义'}</h3><p class="keywords">${both||!rev?c.upKeys:c.revKeys}</p><p>${both||!rev?c.up:c.rev}</p></div>${both?`<div class="meaning"><h3>↓ 逆位释义</h3><p class="keywords">${c.revKeys}</p><p>${c.rev}</p></div>`:''}<div class="meaning"><h3>✧ 占星对应</h3><p class="astro">${c.astro}</p></div>`}
function showInsight(i){const x=picked[i],c=cardById[x.id];$('#insight').innerHTML=`<div class="aside-label">CARD ${String(i+1).padStart(2,'0')} <span>✦</span></div>${activeSpread?`<p class="astro">牌位 ${i+1}：${activeSpread.labels[i]}</p>`:''}${meaning(c,x.rev)}<button class="detail-link" id="fullDetail">查看完整牌义与牌面 ↗</button>`;$('#fullDetail').onclick=()=>openCard(c)}
function reveal(i){if(!picked[i])return;if(picked[i].revealed){showInsight(i);return}const next=picked.findIndex(x=>!x.revealed);if(i!==next){$('#status').textContent=`请先翻开第 ${next+1} 张牌，按抽取顺序揭晓。`;return}const x=picked[i],c=cardById[x.id];x.revealed=true;const btn=$(`[data-picked="${i}"]`);btn.querySelector('.front').innerHTML=image(c,x.rev?'class="reversed"':'');requestAnimationFrame(()=>btn.classList.add('flipped'));btn.setAttribute('aria-label',`第 ${i+1} 张：${c.name}，${x.rev?'逆位':'正位'}，点击查看释义`);btn.nextElementSibling.textContent=`${i+1} · ${c.name} ${x.rev?'逆位':'正位'}`;showInsight(i);$('#reveal').disabled=!picked.some(x=>!x.revealed);$('#status').textContent=`第 ${i+1} 张：${c.name} · ${x.rev?'逆位':'正位'}。${picked.some(x=>!x.revealed)?'继续翻开下一张。':'桌上的牌已全部揭晓，也可以继续选牌。'}`}
function openCard(c){$('#dialogContent').innerHTML=`<div class="detail-layout">${image(c)}<div>${meaning(c,false,true)}</div></div>`;$('#detail').showModal();$('#detail').scrollTop=0}
function gallery(suit='all'){$('#gallery').innerHTML=CARDS.filter(c=>suit==='all'||c.suit===suit).map(c=>`<button class="gallery-card" data-card="${c.id}">${image(c,'loading="lazy" width="350" height="600"')}<h2>${c.name}</h2><p>${c.en}</p></button>`).join('')}
$('#shuffle').onclick=()=>start();$('#reveal').onclick=()=>reveal(picked.findIndex(x=>!x.revealed));$('#placed').onclick=e=>{if(suppressClick){suppressClick=false;return}const b=e.target.closest('[data-picked]');if(b)reveal(+b.dataset.picked)};$('#gallery').onclick=e=>{const b=e.target.closest('[data-card]');if(b)openCard(cardById[b.dataset.card])};$('.filters').onclick=e=>{const b=e.target.closest('[data-suit]');if(!b)return;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===b));gallery(b.dataset.suit)};
function tab(library){$('#spreads').hidden=true;$('#spreadsTab').classList.remove('active');$('#spreadsTab').setAttribute('aria-current','false');$('#reading').hidden=library;$('#library').hidden=!library;$('#tableTab').classList.toggle('active',!library);$('#libraryTab').classList.toggle('active',library);$('#tableTab').setAttribute('aria-current',library?'false':'page');$('#libraryTab').setAttribute('aria-current',library?'page':'false');if(!library)requestAnimationFrame(fitDesktopTable)}
$('#tableTab').onclick=()=>tab(false);$('#libraryTab').onclick=()=>tab(true);$('#closeDialog').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#deck').addEventListener('click',e=>{if(suppressClick){suppressClick=false;return}const b=e.target.closest('[data-index]');if(b){if(window.innerWidth<=800||activeSpread){pendingCard=+b.dataset.index;renderDeck();$('#status').textContent=activeSpread?`已选中牌背，点击第 ${picked.length+1} 格放牌。`:'已选中一张牌背，点击桌布任意空白位置放下。'}else choose(+b.dataset.index)}});
// Positions are normalized to the usable cloth area so resizing preserves the spread.
function boundedPosition(point,width,height,cardWidth,cardHeight){const hx=cardWidth/width/2,hy=cardHeight/height/2;return{x:Math.max(hx,Math.min(1-hx,point.x)),y:Math.max(hy,Math.min(1-hy,point.y))}}
function setPosition(i,point){const el=$(`[data-picked="${i}"]`).parentElement,r=$('#placed').getBoundingClientRect();const pos=activeSpread&&slotGeometry[i]?{x:slotGeometry[i].x,y:slotGeometry[i].y}:boundedPosition(point,r.width,r.height,el.offsetWidth,el.offsetHeight);picked[i].position=pos;el.style.left=pos.x*100+'%';el.style.top=pos.y*100+'%'}
function pointerPoint(x,y){const r=$('#placed').getBoundingClientRect();return{x:(x-r.left)/r.width,y:(y-r.top)/r.height}}
let topLayer=1,scrollFrame=0;
function moveDrag(){if(!drag||!drag.moved||drag.mode==='scroll')return;const d=drag;if(d.kind==='table'){setPosition(d.index,pointerPoint(d.cx-d.offsetX,d.cy-d.offsetY));return}const g=$('#dragGhost');g.hidden=false;g.className='back';g.style.left=d.cx+'px';g.style.top=d.cy+'px';const r=$('#cloth').getBoundingClientRect();$('#cloth').classList.toggle('over',d.cx>=r.left&&d.cx<=r.right&&d.cy>=r.top&&d.cy<=r.bottom)}
function autoScroll(){if(!drag)return;if(drag.moved&&drag.mode!=='scroll'){const y=drag.cy,h=window.innerHeight;const speed=y<90?-Math.ceil((90-y)/6):y>h-90?Math.ceil((y-h+90)/6):0;if(speed){window.scrollBy(0,speed);moveDrag()}}scrollFrame=requestAnimationFrame(autoScroll)}
function beginDrag(e,kind){if(activeSpread&&kind==='table')return;const b=e.target.closest(kind==='deck'?'[data-index]':'[data-picked]');if(!b||shuffling||e.button!==0||drag)return;const index=+(kind==='deck'?b.dataset.index:b.dataset.picked),r=b.parentElement.getBoundingClientRect();drag={kind,index,x:e.clientX,y:e.clientY,cx:e.clientX,cy:e.clientY,moved:false,mode:null,scroll:$('#deck').scrollLeft,pointer:e.pointerId,el:b,offsetX:kind==='table'?e.clientX-r.left-r.width/2:0,offsetY:kind==='table'?e.clientY-r.top-r.height/2:0,original:kind==='table'?{...picked[index].position}:null};if(kind==='table')b.parentElement.style.zIndex=++topLayer;b.setPointerCapture(e.pointerId);scrollFrame=requestAnimationFrame(autoScroll)}
function dragMove(e){if(!drag||e.pointerId!==drag.pointer)return;drag.cx=e.clientX;drag.cy=e.clientY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7)drag.moved=true;if(!drag.moved)return;if(!drag.mode)drag.mode=drag.kind==='deck'&&e.pointerType==='touch'&&Math.abs(e.clientX-drag.x)>Math.abs(e.clientY-drag.y)?'scroll':'drag';if(drag.mode==='scroll'){$('#deck').scrollLeft=drag.scroll-(e.clientX-drag.x);return}e.preventDefault();drag.el.classList.add('dragging');moveDrag()}
function endDrag(e,cancel=false){if(!drag)return;const d=drag;drag=null;cancelAnimationFrame(scrollFrame);$('#dragGhost').hidden=true;d.el.classList.remove('dragging');const r=$('#cloth').getBoundingClientRect(),over=d.cx>=r.left&&d.cx<=r.right&&d.cy>=r.top&&d.cy<=r.bottom;$('#cloth').classList.remove('over');if(d.moved){suppressClick=true;setTimeout(()=>suppressClick=false,350);if(d.kind==='deck'&&d.mode!=='scroll'&&over&&!cancel)choose(d.index,pointerPoint(d.cx,d.cy));if(d.kind==='table'){if(cancel)setPosition(d.index,d.original);else $('#status').textContent=`第 ${d.index+1} 张的位置已调整，抽牌与翻牌顺序保持不变。`}}if(d.el.hasPointerCapture(e.pointerId))d.el.releasePointerCapture(e.pointerId)}
for(const kind of ['deck','table']){const host=$(kind==='deck'?'#deck':'#placed');host.addEventListener('pointerdown',e=>beginDrag(e,kind));host.addEventListener('pointermove',dragMove);host.addEventListener('pointerup',e=>endDrag(e));host.addEventListener('pointercancel',e=>endDrag(e,true));host.addEventListener('lostpointercapture',e=>{if(drag)endDrag(e,true)})}
$('#placed').addEventListener('keydown',e=>{const b=e.target.closest('[data-picked]');if(!b||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const i=+b.dataset.picked,p={...picked[i].position},step=e.shiftKey?.05:.01;if(e.key==='ArrowLeft')p.x-=step;if(e.key==='ArrowRight')p.x+=step;if(e.key==='ArrowUp')p.y-=step;if(e.key==='ArrowDown')p.y+=step;setPosition(i,p)});
new ResizeObserver(()=>{if($('#reading').hidden)return;layoutSlots();picked.forEach((x,i)=>setPosition(i,x.position))}).observe($('#cloth'));
$('#about').onclick=()=>{$('#dialogContent').innerHTML=`<div class="about-text"><p class="eyebrow">ABOUT THIS DECK</p><h2>牌面与对应体系</h2><p>本图鉴使用 1909 年 Rider–Waite–Smith（韦特）塔罗原始画作，由 Pamela Colman Smith 绘制，Arthur Edward Waite 指导。包含 22 张大阿尔卡纳与 56 张小阿尔卡纳；力量为 VIII，正义为 XI。</p><p>占星对应以黄金黎明传统为基础。大牌的星座与行星是不同类别，不把星座的守护星当作该牌直接对应的行星。愚人、倒吊人、审判的传统对应分别为风、水、火；天王星、海王星、冥王星另标为现代补充。太阳与月亮按占星术的星体分类列出。</p><p>数字牌 2–10 标注行星与星座十度区间。王牌与侍从不强行赋予单一行星或星座。宫廷牌有流派差异；这里采用国王对应火性、王后水性、骑士风性、侍从土性的 RWS 转译方案，并列出跨星座区间，不宣称是唯一标准。</p><p>正逆位是现代常见解读方向的中文概括，需结合问题与牌面理解；逆位不等于单纯的坏结果。同一张牌在不同语境中可以有不同侧重。</p><p>洗牌采用随机交换，选牌前牌序与方向已随机确定；每轮抽取不放回。关闭逆位时全为正位，开启时每张牌独立有一半概率逆位。已经选牌后，本轮方向设置锁定，重新洗牌可修改。</p><p>图像来源：<a href="https://github.com/metabismuth/tarot-json" target="_blank" rel="noopener">tarot-json 原始牌面合集</a>（原始画作属公有领域；扫描来源 data.totl.net）。<a href="assets/ATTRIBUTION.txt" target="_blank">图像署名</a> · <a href="assets/SOURCE-LICENSE.txt" target="_blank">来源仓库许可</a></p><p>对应参考：<a href="https://labyrinthos.co/blogs/learn-tarot-with-labyrinthos-academy/astrology-and-tarot-correspondences-the-minor-arcana-pip-cards" target="_blank" rel="noopener">数字牌与十度区间</a> · <a href="https://www.davidcunliffe.com/tarot-astrological-correspondences-of-the-hermetic-order-of-the-golden-dawn/" target="_blank" rel="noopener">占星对应与宫廷牌流派差异</a> · <a href="https://www.pagangrimoire.com/tarot-correspondences-major-arcana/" target="_blank" rel="noopener">大牌传统元素对应</a></p></div>`;$('#detail').showModal();$('#detail').scrollTop=0};
gallery();start();

function fitDesktopTable(){
  // Reserve room for the complete deck below the square in either mode.
  const mobile=window.innerWidth<=800;
  const deckReserve=mobile?255:220;
  const size=Math.max(240,Math.min(600,window.innerHeight-deckReserve-80));
  document.documentElement.style.setProperty('--table-fit',Math.floor(size)+'px');
}
window.addEventListener('resize',fitDesktopTable);
requestAnimationFrame(fitDesktopTable);
if(document.fonts)document.fonts.ready.then(fitDesktopTable);

$('#cancelPick').onclick=()=>{pendingCard=null;renderDeck();$('#status').textContent='已取消选牌，可以重新选择。'};
$('#cloth').addEventListener('click',e=>{if(pendingCard===null||suppressClick||e.target.closest('button,.table-card'))return;choose(pendingCard,pointerPoint(e.clientX,e.clientY))});

new ResizeObserver(()=>requestAnimationFrame(fitDesktopTable)).observe($('.question-field'));

function spreadDiagram(s){return `<svg class="spread-diagram" viewBox="0 0 400 ${s.height||360}" role="img" aria-label="${s.name}摆放示意，牌位含义见下方列表"><title>${s.name}牌位图</title>${s.points.map(([x,y,h],i)=>`<g><rect x="${x-(h?39:24)}" y="${y-(h?18:38)}" width="${h?78:48}" height="${h?36:76}" rx="4" fill="#172536" stroke="#c9aa70"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="#f0d298" font-size="17">${s.slotNames?.[i]??i+1}</text></g>`).join('')}</svg>`}
function spreadBody(s){return `${spreadDiagram(s)}<ol class="spread-positions">${s.labels.map(t=>`<li>${t}</li>`).join('')}</ol>`}
$('#spreadGrid').innerHTML=SPREADS.map((s,i)=>`<article class="spread-guide"><div class="spread-title"><h2>${s.name}</h2><span>${s.points.length} 张</span></div><p class="spread-use">${s.use}</p><p class="spread-example">例如：${s.example}</p>${spreadBody(s)}${s.note?`<p class="spread-note">${s.note}</p>`:''}<button type="button" class="gold" data-spread="${i}">带着这个牌阵去抽牌 ↗</button></article>`).join('');
$('#spreadsTab').onclick=()=>{$('#reading').hidden=true;$('#library').hidden=true;$('#spreads').hidden=false;document.querySelectorAll('nav .nav').forEach(b=>{const active=b.id==='spreadsTab';b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')})};
$('#spreadGrid').onclick=e=>{const b=e.target.closest('[data-spread]');if(!b)return;e.preventDefault();enterSpread(SPREADS[Number(b.dataset.spread)])};
new ResizeObserver(()=>requestAnimationFrame(fitDesktopTable)).observe($('#spreadReference'));

$('#placed').addEventListener('click',e=>{const b=e.target.closest('[data-rotate]');if(!b||activeSpread)return;e.stopPropagation();const i=+b.dataset.rotate,x=picked[i];x.horizontal=!x.horizontal;b.parentElement.classList.toggle('horizontal',x.horizontal);b.parentElement.style.zIndex=++topLayer;b.setAttribute('aria-pressed',String(x.horizontal));b.setAttribute('aria-label',`将第 ${i+1} 张牌${x.horizontal?'竖放':'横放'}`);setPosition(i,x.position);$('#status').textContent=`第 ${i+1} 张已${x.horizontal?'横放':'竖放'}，正逆位与翻牌顺序保持不变。`});

function insideSlot(point,g){return !!g&&Math.abs(point.x-g.x)<=g.w/2+.025&&Math.abs(point.y-g.y)<=g.h/2+.025}
function layoutSlots(){
  const layer=$('#slotLayer');if(!activeSpread){layer.innerHTML='';slotGeometry=[];return}
  const r=$('#placed').getBoundingClientRect();if(!r.width||!r.height)return;
  const height=activeSpread.height||360,unit=Math.min(r.width/424,r.height/(height+24));
  const cardW=Math.max(30,Math.min(62,r.width*.11)),cardH=cardW*600/350;
  slotGeometry=activeSpread.points.map(([x,y,h])=>({x:(r.width/2+(x-200)*unit)/r.width,y:(r.height/2+(y-height/2)*unit)/r.height,w:(h?cardH:cardW)/r.width,h:(h?cardW:cardH)/r.height}));
  layer.innerHTML=slotGeometry.map((g,i)=>`<button class="spread-slot ${i===picked.length?'next-slot':''}" style="left:${g.x*100}%;top:${g.y*100}%;width:${g.w*100}%;height:${g.h*100}%" data-slot="${i}" ${i!==picked.length?'disabled':''} aria-label="${activeSpread.slotNames?.[i]??`第 ${i+1} 格`}：${activeSpread.labels[i]}" ${i<picked.length?'hidden':''}>${activeSpread.slotNames?.[i]??i+1}</button>`).join('');
  picked.forEach((x,i)=>{const g=slotGeometry[i],el=$(`[data-picked="${i}"]`).parentElement;el.style.width=g.w*100+'%';el.style.maxWidth='none';setPosition(i,{x:g.x,y:g.y})});
}

function enterSpread(s){
  clearTimeout(shuffleTimer);shuffling=false;
  activeSpread=s;$('#reading').classList.toggle('fixed-spread',!!s);$('#freeMode').hidden=!s;$('#modeLabel').textContent=s?`${s.name} · 按编号放入 ${s.points.length} 张牌`:'自由抽牌 · 任意摆放';
  $('#spreadReference').hidden=!s;$('#spreadReference').open=false;
  if(s){$('#spreadSummary').textContent=`查看${s.name}的牌位含义`;$('#spreadReferenceContent').innerHTML=spreadBody(s)}
  tab(false);start(true,true);requestAnimationFrame(()=>{fitDesktopTable();layoutSlots();window.scrollTo({top:Math.max(0,$('#modeBar').getBoundingClientRect().top+window.scrollY-12),behavior:'auto'})});
}
$('#freeMode').onclick=()=>enterSpread(null);
$('#slotLayer').onclick=e=>{const b=e.target.closest('[data-slot]');if(!b||pendingCard===null||suppressClick)return;const i=+b.dataset.slot;if(i!==picked.length)return;choose(pendingCard,{x:slotGeometry[i].x,y:slotGeometry[i].y})};
